### ISSUE TITLE
feat(types): Replace current types and codegen with type-rs types

### ISSUE THREAD

**Issue by antiyro** [madara-alliance/madara#187] opened 2024-06-28 15:46 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Motivation

We aim to remove our dependency on `starknet-rs` because it does not provide the necessary infrastructure tools in a timely manner and is more oriented towards application development on Starknet.

Currently, we have two primary uses of `starknet-rs`:
1. The `SequencerGatewayProvider`, which synchronizes blocks, state updates, and classes from the sequencer. (#186)
2. The codegen, which helps us build our RPC methods while adhering to the latest specifications.(#382)

### Request

The goal is to eliminate our use of the types from the `starknet-rs` core crate types in favor of those from `type-rs`. This will allow us to keep up with new releases in a timely manner.

The types from `starknet-rs` are located [here](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types), and the codegen from `type-rs` is located [here](https://github.com/starknet-io/types-rs/tree/main/crates/starknet-types-rpc).

We need to replace our current use of types from `starknet-rs` codegen with those from `type-rs`. This involves modifying all RPC-related types and adapting execution such as blockifier, `from_broadcasted_tx`, etc.

This issue may invoke some changes in type-rs for missing types. Please feel free to discuss it under this issue.

### Solution

Replace all the types from starknet-rs with type-rs types.

### Are you willing to help with this request?

Yes!

**Comment by Trantorian1** [comment] 2024-12-10 16:17
This is a duplicate of #382

**Closed as completed by Trantorian1** 2024-12-10 16:17 UTC
Labels: feature, help-wanted
